export type Role = "user" | "assistant" | "tool" | "error";
export type SearchHit = { path: string; line: number; column: number; text: string };
export type FileEntry = { name: string; path: string; kind: "dir" | "file"; depth: number };
export type GitStatusEntry = { path: string; status: string; raw: string };
export type GitStatus = { branch: string; entries: GitStatusEntry[] };
export type Message = { role: Role; content: string };
export type TextSnapshot = { value: string; selectionStart: number; selectionEnd: number };
export type MessageGroup = { key: string; kind: "message"; message: Message } | { key: string; kind: "tools"; tools: Message[] };
export type WorkspaceOption = { path: string; name: string; deletable: boolean };
export type SessionOption = { id: string; title: string; preview: string; message_count: number; updated_at: number; running: boolean };
export type SessionInfo = { workspace: string; active_session_id: string; messages: Message[]; sessions: SessionOption[]; workspaces: WorkspaceOption[] };
export type ChatStreamEvent = { id?: string; session_id: string; kind: "start" | "delta" | "tool" | "done" | "error" | "usage"; role?: Role; text?: string; content?: string; debug?: string; input_tokens?: number; output_tokens?: number; total_tokens?: number };
export type FileChangedEvent = { workspace: string; paths: string[] };
export type ProviderOption = { name: string; kind: string; api_base: string; api_key_header: string; has_api_key: boolean };
export type ModelOption = { name: string; provider: string; id: string; context_chars: number };
export type ThinkingLevel = "auto" | "low" | "medium" | "high";
export type AgentOption = { name: string; description: string; persona: string; thinking_level: ThinkingLevel; prompt_injection: string };
export type SubagentOption = { name: string; description: string; system: string; model: string; max_result_chars: number };
export type ExtensionToolInfo = { name: string; description: string };
export type ExtensionInfo = { id: string; name: string; enabled: boolean; removable: boolean; description: string; path?: string; hooks: string[]; tools: ExtensionToolInfo[] };
export type ExtensionsInfo = { config_path: string; extensions: ExtensionInfo[] };
export type McpServer = { name: string; command: string; args: string[]; timeout_ms: number; env: Record<string, string> };
export type McpServerDraft = { name: string; original_name: string; command: string; args: string; timeout_ms: number; env: string };
export type AiMods = {
  main_model: string;
  main_agent: string;
  subagents: string[];
  persona: string;
  thinking_level: ThinkingLevel;
  prompt_injection: string;
  rtk_enabled: boolean;
  shell_enabled: boolean;
  git_panel_enabled: boolean;
  subagents_enabled: boolean;
  subagent_model: string;
  subagent_max_concurrency: number;
  subagents_config: string;
  mcp_enabled: boolean;
  mcp_config: string;
};
export type ProfileOption = AiMods & { name: string };
export type AiConfig = {
  config_dir: string;
  provider: string;
  api_base: string;
  model: string;
  model_id: string;
  context_chars: number;
  has_api_key: boolean;
  providers: ProviderOption[];
  models: ModelOption[];
  features: Record<string, boolean>;
  mods: AiMods;
  active_profile: string;
  profiles: ProfileOption[];
  agents: AgentOption[];
  subagents_registry: SubagentOption[];
  rtk_available: boolean;
  ui_scale: number;
};
